### ISSUE TITLE
(Heloiza, Danilo) Implementar primeira versão do Front com form para gerar planeta

### ISSUE THREAD

**Issue by KaiqueBahmad** [KaiqueBahmad/orbit-simulator#5]
Form deve pedir os atributos posição (x, y) velocidades iniciais (vx, vy) e massa

**Comment by Isaluh** [comment]
![image](https://github.com/KaiqueBahmad/orbit-simulator/assets/82837765/7021065c-1cd9-4096-a58a-3eab346a3159)

**Comment by Isaluh** [comment]
troca a extensao pra .ui
[qtView.txt](https://github.com/KaiqueBahmad/orbit-simulator/files/15300414/qtView.txt)

**Comment by Isaluh** [comment]
[orbit-simulator.zip](https://github.com/KaiqueBahmad/orbit-simulator/files/15311219/orbit-simulator.zip)
zip do ui. com a pasta assets
